server:
  port: 8081
spring:
  #移到bootstrap.yml中
#  application:
#    name: userservice
  datasource:
#    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    # 容器化部署，localhost换成docker-compose-yml中配置的 mysql
    url: jdbc:mysql://mysql:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #nacos
  cloud:
    nacos:
#      server-addr: localhost:81
#      server-addr: localhost:8848
      # 容器化部署方式 改为nacos:8848
      server-addr: nacos:8848 # nacos地址,从nacos中获取微服务的地址
      discovery:
        cluster-name: SH #用nacos将其归属上海集群
#        namespace: e6ca71b9-2a79-4fb6-aaf7-14e67a51f159
#        ephemeral: false # 设置为非临时实例
#        group: group1 #组

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
#  instance: # 在Eureka中显示服务的ip地址
#    ip-address: 127.0.0.1 # 配置服务器ip地址
#    prefer-ip-address: true # 更倾向于使用ip,而不是host名
#    instance-id: ${eureka.instance.ip-address}:${server.port} # 自定义实例的id
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

# 自定义配置
#pattern:
#  dataformat: yyyy-MM-dd HH:mm:ss
